### ISSUE TITLE
Problem with (Object::IsValid(trade[tfi].Chart()) && trade[tfi].Chart().IsValidTf() in InitInfo when debugging

### ISSUE THREAD

**Issue by soumsena** [EA31337/EA31337#105] opened 2019-02-09 11:56 UTC
EA31337 EURUSD,M15: invalid pointer access in 'EA31337.mq4' (584,25)

**Comment by soumsena** [comment] 2019-02-09 11:57
![1](https://user-images.githubusercontent.com/40273435/52520415-d647f280-2c61-11e9-9808-e9dc6f3045f6.png)
![2](https://user-images.githubusercontent.com/40273435/52520416-d6e08900-2c61-11e9-9eef-c1a89c8183bc.png)

**Comment by kenorb** [comment] 2019-02-09 20:28
Could you change that line to:
```
if (Object::IsDynamic(trade[tfi]) && trade[tfi].Chart().IsValidTf()) {
```
Basically `Object::IsValid` to `Object::IsDynamic`.

The aim of the code is to check whether `trade[tfi]` object has been initialized correctly.

**Comment by kenorb** [comment] 2019-02-09 20:36
I've applied the change in b3af0f17c062c2de1ee15a4ef25d4b439e0ee2b6.

**Comment by soumsena** [comment] 2019-02-09 21:59
thx for your reply, it is exact, the trade[tfi] object has not been initialized correctly, the issue is in function InitClasses at line 5046 "trade_params.chart = _chart;"

**Comment by soumsena** [comment] 2019-02-10 10:00
![10](https://user-images.githubusercontent.com/40273435/52532305-84af6e80-2d1a-11e9-811c-690427f1e1e0.png)
![11](https://user-images.githubusercontent.com/40273435/52532306-84af6e80-2d1a-11e9-8add-efa523ce08fb.png)

**Comment by soumsena** [comment] 2019-02-10 10:03
trade_param value:
Trade{  
         trade_params: 
              TradeParams{  
                   slippage:0 
                   account:Account{  snapshots:[] init_balance:1000.0 start_balance:1000.0 start_credit:1000.0 
                                               acc_stats:[6][3][3][2] trades:Orders{  pool:ORDERS_POOL_TRADES orders:[] 
                                           logger:Log{  filename:"Log.txt" data:[… }… }

**Comment by soumsena** [comment] 2019-02-10 10:05
@kenord, thx for your help

**Comment by kenorb** [comment] 2019-02-10 15:52
![](https://user-images.githubusercontent.com/40273435/52532305-84af6e80-2d1a-11e9-811c-690427f1e1e0.png)

I can't see anything wrong in above screenshot.
The code is in the loop, where `tfi` increases from 0, so at this moment when you're in line 5047, it's correct that `trade[tfi]` is NULL, because you're about to assign to it in the next 2 lines (line 5049). So each time when `tfi` is increased, `trade[tfi]` points to NULL, and at line 5049 it should be assigned correctly.
Using `_chart` is also correct, and it's defined in line 5043 for each timeframe which is active. Since condition `_chart.IsValidTf()` passed, that means we've valid `_chart` (not `chart`), and you can see on the screenshot that `_chart` is correctly initialized for the M15. The global `chart` (not `_chart`) isn't used anywhere, that's why it's NULL. And `trade_params.chart` is the item of struct which is defined in Trade class, so it needs to be `chart`, not `_chart`.
So currently I don't see any issue in the logic.

**Comment by kenorb** [comment] 2019-02-10 15:58
![](https://user-images.githubusercontent.com/40273435/52532306-84af6e80-2d1a-11e9-8add-efa523ce08fb.png)

In above screenshot, `trade[tfi]` should return instance of `Trade` class, where `trade[tfi].Chart()` should return instance of `Chart` class for the given timeframe identified by `tfi` (timeframe index). This cannot be seen in the screenshot, as the vale is cut off.
In the screenshot above, I can see that `trade[tfi]` has the right instance of `Trade` class. I can see that `trade_params.account` has the right instance of `Account` class. The screenshot doesn't show `Chart` instance, as the value is cut off by `...`.
So I can't see any obvious issues in this screenshot either.
I'll have to debug the code myself and check. I'll try somewhere next week.

**Comment by soumsena** [comment] 2019-02-10 17:20
ok

**Comment by soumsena** [comment] 2019-02-10 17:45
@kenork, as the value is cut off by ..... how can i do to see the whole instance of `Trade` class, so that I can manipulate it???

**Comment by soumsena** [comment] 2019-02-10 18:04
I wanted to thank you sincerely for the great job you did. when I read your code, it is so clear and ingenious, it makes me look for and become stronger. I do not sleep anymore because of that. I wonder how you could learn the trading system and programming and become a master.

**Comment by kenorb** [comment] 2019-02-10 18:22
> @kenork, as the value is cut off by ..... how can i do to see the whole instance of `Trade` class, so that I can manipulate it???

The best is to narrow down the variable in the debugger expression list. For example, `trade[tfi]` can be broken down by:
- `trade[tfi].trade_params.account` or trade[tfi].Account()`,
- `trade[tfi].trade_params.chart` or trade[tfi].Chart()`,
- or any of trade params defined in `Trade.mqh` as per `TradeParams` definition.
- Also at the bottom of the `Trade.mqh` file you can find class handlers which `Trade` can support.

**Comment by kenorb** [comment] 2019-02-10 18:27
> I wanted to thank you sincerely for the great job you did. when I read your code, it is so clear and ingenious, it makes me look for and become stronger. I do not sleep anymore because of that. I wonder how you could learn the trading system and programming and become a master.

No worries, I'll try to fix these errors, so you can sleep more. When operating on object oriented code (classes and so on), it's more difficult to manage, since you've to worry about that kind of errors, where pointers aren't valid.
I don't teach trading, since I'd like to focus on EA in my free time. There is still a lot of work to be done. The purpose of this EA is actually for encourage people to learn trading on them-self.

**Comment by kenorb** [comment] 2019-02-10 21:17
I've run debugger and I was able to reproduce the issue.

The issue has been fixed in 799fdd884292ddc438151e7cd981cfb760f02622 and 064f69f6e050cce77c94e2ae3a02694086b6a2ca

**Closed by kenorb** 2019-02-10 21:17 UTC
Labels: bug

**Comment by kenorb** [comment] 2019-02-10 21:28
However, I think the fix could caused some regression as per GH-106.

**Comment by soumsena** [comment] 2019-02-10 21:37
@kenorb , thank you for replying and your help. the issue has fixed
